---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flux-source
  namespace: flux-system
spec:
  interval: 12h0m0s
  provider: generic
  ref:
    tag: latest
  url: oci://ghcr.io/fluxcd/flux-manifests #oci://kind-registry:5000/flux
  insecure: true
